// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBObU730-6whQWrHqdghCP-vXEDgwPQwOY',
    appId: '1:821142592803:web:5fd0c6dcd397f6b4dcc096',
    messagingSenderId: '821142592803',
    projectId: 'dhanyasethu-8d886',
    authDomain: 'dhanyasethu-8d886.firebaseapp.com',
    storageBucket: 'dhanyasethu-8d886.firebasestorage.app',
    measurementId: 'G-X9QREMD543',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfzZM5v_LXURbwr759Yc8WnxiIPxpwnos',
    appId: '1:821142592803:android:990e0cc9b822082adcc096',
    messagingSenderId: '821142592803',
    projectId: 'dhanyasethu-8d886',
    storageBucket: 'dhanyasethu-8d886.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK8ivnaFe8tqMoomdspKvKT5qWD6Cb9_4',
    appId: '1:821142592803:ios:08a2279f403a0e40dcc096',
    messagingSenderId: '821142592803',
    projectId: 'dhanyasethu-8d886',
    storageBucket: 'dhanyasethu-8d886.firebasestorage.app',
    iosBundleId: 'com.example.talentfarm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK8ivnaFe8tqMoomdspKvKT5qWD6Cb9_4',
    appId: '1:821142592803:ios:08a2279f403a0e40dcc096',
    messagingSenderId: '821142592803',
    projectId: 'dhanyasethu-8d886',
    storageBucket: 'dhanyasethu-8d886.firebasestorage.app',
    iosBundleId: 'com.example.talentfarm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBObU730-6whQWrHqdghCP-vXEDgwPQwOY',
    appId: '1:821142592803:web:97e2892f77c0b325dcc096',
    messagingSenderId: '821142592803',
    projectId: 'dhanyasethu-8d886',
    authDomain: 'dhanyasethu-8d886.firebaseapp.com',
    storageBucket: 'dhanyasethu-8d886.firebasestorage.app',
    measurementId: 'G-BTD75Y7T6V',
  );
}
